### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by capriciousduck** [kibitzr/kibitzr#103]
How to make this app run on Heroku. Is there a $PORT functionality for this app?

**Comment by peterdemin** [comment]
Kibitzr doesn’t have a web UI by design. This makes it a bad fit for Heroku.
Personally, I host kibitzr on a home server using systemd unit and on a Google Cloud Platform using docker deployed to an always-free VM instance.

**Comment by capriciousduck** [comment]
Oh. Okay.
