### ISSUE TITLE
Is it possible to run code once at first startup?

### ISSUE THREAD

**Issue by philipsd6** [kibitzr/kibitzr#112]
I have an API that takes > 10 seconds on the first execution, but thereafter, API calls are very quick. Is it possible to initialize that API once at startup, and then save the API object somewhere where it can be reused in other checks without the overhead of the first call? I see there's a `kibitzr.before_start` hook, but it looks like it gets called every time through the run loop, and I want to only run it once before the run loop.

**Comment by peterdemin** [comment]
I'm using Stash for this purpose: https://kibitzr.readthedocs.io/en/latest/stash.html
