### ISSUE TITLE
smtp notifier tries to login with blank credentials

### ISSUE THREAD

**Issue by QJKX** [kibitzr/kibitzr#121]
The smtp server I'm using has nothing to do with the recipient address.
kibitzr tries to login with an irrelevant value `user`  which makes  the server disconnect (501).

The expected behavior is for kibitzr to only try to login if the username and password are present in the config.

Suggested fix:
Default `user` and `password` to None. 

    user = credentials.get('user', None)
    password = credentials.get('password', None)

Only attempt a  login if the password has been configured.

    if password is not None:
        server.login(user, password)

**Comment by peterdemin** [comment]
Makes sense. Could you open a PR?

**Comment by peterdemin** [comment]
Thanks!
