### ISSUE TITLE
Docker image failed to update

### ISSUE THREAD

**Issue by mcrozz** [kibitzr/kibitzr#143]
Latest version on docker hub is 7.0.5. Seems like job failed:

https://github.com/kibitzr/kibitzr/actions/runs/7427870480/job/20214276680

**Comment by peterdemin** [comment]
Bumped version to trigger Docker build.

**Comment by peterdemin** [comment]
Upgraded a couple of packages that were failing to install, and the docker job succeeded. Thanks for bringing this up.
Please try the new release.

**Comment by mcrozz** [comment]
Thank you!
