### ISSUE TITLE
Windows doesn't support SIGUSR1

### ISSUE THREAD

**Issue by peterdemin** [kibitzr/kibitzr#73]
Looks like kibitzr fails under Windows. Need to take a look.

**Comment by seadoggie01** [comment]
This is still an issue :( There is a try/catch later in the file 'app.py' for SIGUSR1/2, but the error is thrown in the __init__ function.
If you need help debugging/checking this, I'd be glad to help! I code, but don't know a ton of python.

**Comment by peterdemin** [comment]
I'd be happy to review your PR

**Comment by seadoggie01** [comment]
And I'd be happy to commit, but I

> don't know a ton of python.

... by that I mean... I can't submit a PR, because I can't code well enough to understand what's going on

**Comment by peterdemin** [comment]
I just release 6.0.0, could you please verify, that it works under Windows?

**Comment by seadoggie01** [comment]
The example from the docs (https://kibitzr.readthedocs.io/en/latest/configuration.html) is working. I can't find my previous script that stopped working, but I'll keep checking. Thank you! :)
