### ISSUE TITLE
Commit changes to git repos after successfully notifying?

### ISSUE THREAD

**Issue by karlicoss** [kibitzr/kibitzr#74]
Currently kibitzr commits in the underying git repo first; and then notifies. So, if a notification fails (e.g. expired api key/network glitch/whatever), you will miss the change. 
I guess an easier way to deal with it would be just to undo the latest commit if some of the notification methods failed?

Another issue is: if one of the notifiers fails, the whole program still exits with 0 exit code which makes it a bit harder to track failures. Do you think it makes sense to exit with nonzero code in that case? 

Let me know if you think that makes sense; I'll be happy to implement and contribute!

**Comment by peterdemin** [comment]
Hi Dmitrii, error handling is hard and I didn't want to complicate Kibitzr configuration syntax with all possible options. If you are looking for error notifications, give [kibitzr-sentry](https://github.com/kibitzr/kibitzr-sentry) a try, I use it and it fits sentry.io free plan.

I don't think, that rolling back is an option. Consider cases:

1. It's the first commit, so the whole repo has to be deleted.
2. One of 2 notifiers failed, but the one that worked can't be repeated.

As a side note, if notification fails, `kibitzr run` doesn't exit, but continues running. I think you are talking about `once` command. But even in that mode, it will run remaining checks and some of them may succeed, some fail. So, in this case, kibitzr itself works fine and exits with 0 code. I guess we can add an option like `--fail-fast` which will immediately halt kibitzr on the first error in any part of any check.
