### ISSUE TITLE
Geckodriver issue - NetworkError

### ISSUE THREAD

**Issue by ColdIce1** [kibitzr/kibitzr#77]
Hello,

I'm having an issue running latest docker image published on my system.
I discovered that Geckodriver is broken, manually updating the driver inside the images to latest v0.23 fixes the issue (from https://github.com/mozilla/geckodriver/releases/tag/v0.23.0 )

Log below:

> 1545203408943   geckodriver     INFO    geckodriver 0.20.1
1545203408955   geckodriver     INFO    Listening on 127.0.0.1:53944
1545203409964   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-headless" "-profile" "/tmp/rust_mozprofile.oJMjQRxZqm9Q"
*** You are running in headless mode.
1545203411205   Marionette      DEBUG   Received observer notification profile-after-change
1545203411678   Marionette      DEBUG   Received observer notification command-line-startup
1545203411679   Marionette      DEBUG   Received observer notification nsPref:changed
1545203411679   Marionette      DEBUG   Init aborted (running=false, enabled=true, finalUIStartup=false)
1545203412747   Marionette      DEBUG   Received observer notification toplevel-window-ready
1545203414939   Marionette      DEBUG   Received observer notification sessionstore-windows-restored
1545203414940   Marionette      DEBUG   Waiting for delayed startup...
1545203415237   Marionette      DEBUG   Setting recommended pref app.update.disabledForTesting to true
1545203415237   Marionette      DEBUG   Setting recommended pref security.turn_off_all_security_so_that_viruses_can_take_over_this_computer to true
1545203415241   Marionette      DEBUG   Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1545203415242   Marionette      DEBUG   Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1545203415243   Marionette      DEBUG   Setting recommended pref dom.disable_beforeunload to true
1545203415379   Marionette      INFO    Listening on port 59003
1545203415380   Marionette      DEBUG   Remote service is active
1545203415392   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:60704
1545203415404   Marionette      TRACE   0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"br$
1545203415405   Marionette      TRACE   0 <- [1,1,{"error":"unknown command","message":"newSession","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178: ... et@chrome$
console.error: BroadcastService:
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:721:13

**Comment by peterdemin** [comment]
Thanks for the heads up. Could you please put the fix in the PR?

**Comment by ColdIce1** [comment]
Issue resolved.

**Comment by peterdemin** [comment]
Thanks for the confirmation
