### ISSUE TITLE
Add matrix notifier

### ISSUE THREAD

**Issue by ptman** [kibitzr/kibitzr#90]
Quite easy to send:

    PUT /_matrix/client/r0/rooms/{roomid}/send/m.room.message/{txnid}
    Authorization: Bearer {accesstoken}
    Content-Type: application/json
    
    {"msgtype": "m.notice", "body": "{message}"}

https://matrix.org/docs/spec/client_server/r0.6.0#put-matrix-client-r0-rooms-roomid-send-eventtype-txnid

**Comment by peterdemin** [comment]
I'm not matrix user, but I'd be happy to review the PR
